# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='О нас')),
                ('slogan', models.CharField(max_length=50, verbose_name='Слоган 50 символов')),
            ],
            options={
                'verbose_name_plural': 'О нас',
                'verbose_name': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='ActionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок Акции 50 символов')),
                ('actiontext', models.CharField(max_length=60, verbose_name='Краткий текст Акции 60 символов')),
                ('actionbigtext', models.CharField(max_length=200, verbose_name='Текст Акции 200 символов')),
                ('btntext', models.CharField(max_length=25, verbose_name='Кнопка 25 символов')),
                ('imageA', models.ImageField(upload_to='action/%Y/%m/%d/', verbose_name='Фото акции (мал. 570x296)')),
                ('imageB', models.ImageField(upload_to='banner/%Y/%m/%d/', verbose_name='Баннер на Главной (бол. 1605x660)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Акции на Главной',
                'ordering': ['created'],
                'verbose_name': 'Акция на Главной',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name_plural': 'Цвета',
                'ordering': ['name'],
                'verbose_name': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='ContactsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(verbose_name='Адрес')),
                ('route', models.TextField(verbose_name='Описание маршрута')),
            ],
            options={
                'verbose_name_plural': 'Адрес и Маршрут',
                'verbose_name': 'Адрес и Маршрут',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliver', models.TextField(verbose_name='О Доставке')),
                ('slogan', models.CharField(max_length=50, verbose_name='Слоган 50 символов')),
            ],
            options={
                'verbose_name_plural': 'О Доставке',
                'verbose_name': 'О Доставке',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
                'verbose_name': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='GoodName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Названия',
                'ordering': ['name'],
                'verbose_name': 'Название',
            },
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(db_index=True, default='Администрация', max_length=50, verbose_name='Автор')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('news', models.TextField(verbose_name='Новость')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Фото новости 870x400')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'ordering': ['created'],
                'verbose_name': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара 750x1000')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Занесен')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('recommended', models.BooleanField(default=False, verbose_name='Рекоммендуемый')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='shop.Category', verbose_name='Категория')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.Color', verbose_name='Цвет')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firms', to='shop.Firm', verbose_name='Производитель')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodnames', to='shop.GoodName', verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('author', models.CharField(db_index=True, max_length=50, verbose_name='Автор')),
                ('email', models.EmailField(max_length=80, verbose_name='Почта')),
                ('ratingcomment', models.TextField(verbose_name='Отзыв')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Оставлен')),
                ('flag', models.BooleanField(default=False, verbose_name='Отобразить на сайте')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='shop.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['-created'],
                'verbose_name': 'Рейтинг',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sz', models.CharField(choices=[('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('36/39', '36/39'), ('40/43', '40/43'), ('N', 'Нет')], db_index=True, max_length=5, unique=True, verbose_name='Размер')),
            ],
            options={
                'verbose_name_plural': 'Размеры',
                'ordering': ['sz'],
                'verbose_name': 'Размер',
            },
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Тип')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Типы',
                'ordering': ['name'],
                'verbose_name': 'Тип',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.Size', verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='tips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Tips', verbose_name='Тип'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
